version: "3.8"

services:
  frontend:
    image: matchingapp-frontend:latest
    container_name: matchingapp_frontend
    ports:
      - "4000:4000"
    volumes:
      - .:/app/
      - /app/node_modules
