version: "3"

services:
  db:
    image: postgres
    container_name: matchingapp_db
    ports: ["5435:5432"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "matchingapp"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  web:
    image: matchingapp-web:latest
    container_name: matchingapp_web
    ports: [ "8086:8080" ]
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: "matchingapp"
    volumes:
      - ./matchingapp/:/app/
    depends_on:
      - db

  frontend:
    image: matchingapp-frontend:latest
    container_name: matchingapp_frontend
    ports: [ "4000:4000" ]
    volumes:
      - ./frontend/:/app/
      - /app/node_modules

volumes:
  postgres-data:
