# Generated by Django 5.0.4 on 2024-04-27 06:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchReject',
            new_name='Dislike',
        ),
    ]
