# Generated by Django 5.0.4 on 2024-04-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_matchreject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchRequest',
            new_name='Like',
        ),
    ]
