# Generated by Django 5.0.4 on 2024-04-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_matchrequest_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='matchreject',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='matchreject',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='MatchReject',
        ),
    ]
